<div id="ram" style="font-weight: normal;">
    <h1><?= $titulek ?></h1>

    </br>Kontaktní osoba: <b>XY</b> 
    </br> Telefon: <b>666 466 566 </b> 
    e-mail: <b>info@pujcovna.cz</b> 
    </br>Adresa: <b>U pujcovny 32 326 00 Plzeň </b>
    </br></br>Číslo účtu pro platby EUR ze Slovenska : <b>222222/8330 Fiobanka</b>
    </br>Číslo účtu pro ostatní platby  platby :  <b>3333333/3030 Air bank</b>
    <br />

</div>
